---
# defaults file for tripleo_cluster_deploy
tripleo_cephadm_services:
  - mon
  - mgr
  - osd
# leaving an empty data_devices result in --all-available-devices
data_devices: []
use_labels: false
use_pattern: true
dest_path: /etc/ceph
ceph_template_list:
  - spec.yaml
  - host.yaml

labels:
  ceph_mon:
    - mon
    - mgr
    - mds
    - rgw
    - grafana
    - prometheus
    - node-exporter
    - alertmanager
  ceph_osd:
    - osd
    - node-exporter

