---
- hosts: localhost
  vars:
    tripleo_overcloud_config_download_path: "/home/stack/overcloud/config-download"
    tripleo_overcloud_cephadm_home: "{{ tripleo_overcloud_config_download_path }}/cephadm"
    tripleo_overcloud_inventory: "{{ tripleo_overcloud_config_download_path }}/tripleo-ansible-inventory.yaml"
  tasks:
    - name: Ensure the cephadm dir exist
      file:
        path: "{{ tripleo_overcloud_config_download_path }}/cephadm"
        state: "directory"

    - name: Link the ceph compatible inventory
      file:
        src: "{{ tripleo_overcloud_inventory }}"
        dest: "{{ tripleo_overcloud_cephadm_home }}/inventory.yaml"
        owner: stack
        group: stack
        state: link
